### PR TITLE
Autoloads cookie and minor refactors

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**

### CODE REVIEW

**Comment by purcell** [comment]
Also: `smoke`, `flame`, `gotoxy` etc. all need to be prefixed with `fireplace-`.

**Comment by AdrieanKhisbe** [comment]
@johanvts, I applied all the other @purcell's [recommandation](https://github.com/milkypostman/melpa/pull/3403#issuecomment-165906635) so that fireplace hits melpa

I took the liberty to downgrade the version to 0.1 so far. waiting for some stability to hit the `1.0`

If you want help in setting up  easily few test and CI, just ping me or have a look to [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el)

**Comment by johanvts** [comment]
Thanks a lot, this is a lot cleaner :+1: One concern is it that the program controlled variables are now also prefixed with ''fireplace-'', it makes it difficult for the user to know what he can set and what will be defined by the program. But I guess that should be handled using variable grouping.

**Comment by AdrieanKhisbe** [comment]
I can set up customs if you want.
So that it uses standard emacs configuration

**Pull request merged**
