### PR TITLE
Add sound feature

### PR DESCRIPTION
**Pull request by KaratasFurkan**

### CODE REVIEW

**Review by kadircancetin — APPROVED** [review]

**Comment by AdrieanKhisbe** [comment]
Hello @KaratasFurkan, following up on your mail I lately saw:

I think the best to test out your feature is via an integration test

For instance something like
```cucumber
  Scenario: Turn on the fire make it noisy then not
    When I call "fireplace"
    And  I switch to buffer "*fireplace*"
    And  I call "fireplace-toggle-sound"
    And  I wait for 1 second
    And  I call "fireplace-toggle-sound"
```

in the file https://github.com/johanvts/emacs-fireplace/blob/master/features/emacs-fireplace.feature

I can try to do it directly if you allow me to push on your branch

**Comment by KaratasFurkan** [comment]
Hello @AdrieanKhisbe, thanks for help. I send you an invitation.

**Comment by AdrieanKhisbe** [comment]
@KaratasFurkan received :), let see how 0dfb22a goes

**Review by seyyidibrahimgulec — APPROVED** [review]

**Review by AdrieanKhisbe — APPROVED** [review]
If you want @johanvts, I can have it merge, bump the version and add a tag for melpa.

**Comment by johanvts** [comment]
Nice work, go ahead @AdrieanKhisbe

**Comment by AdrieanKhisbe** [comment]
@johanvts Here it is: f6c23e2 [v1.2.0](https://github.com/johanvts/emacs-fireplace/releases/tag/v1.2.0) :sound:

**Pull request merged**
