### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Seting up CI, and tests scaffolds.

(travis and coveralls have to be activated :))

revert disable undo duplicate

### CODE REVIEW

**Comment by johanvts** [comment]
Thanks for putting in so much work. Is this only support for automated tests or does it also contain some tests? And in that case which file describes the tests?

I think adding this functionality mostly makes sense if we plan a lot of future development, which I don't currently. I am pretty happy with having this be a simple project that does something fun and also is easy to figure out for other first time developers. Another part of it is that I want to use as few features as possible because of compatibility and performance reasons. If the fireplace is running while emacs is in use the CPU draw is already close the limit. 

However, it would also be cool to build the best looking fireplace possible, but it's not something I'm up for at the moment. But if you want to run wild with it perhaps we could add a `fireplace-fancy` command or have some other way of doing both and I could add you to the project to work on that part as primus motor. What do you think?

**Comment by AdrieanKhisbe** [comment]
No test so far, but I plan to do some.
At least to ensure that fireplace can executes.

currently working on faces

**Comment by AdrieanKhisbe** [comment]
definitely some improvement could be made to it to be less ressources consuming.
Test would ensure no regression occures.

**Comment by johanvts** [comment]
What faces would you like to change?
If you have any great optimizations I would love to merge them in as long as the code remains readable :)

**Comment by AdrieanKhisbe** [comment]
want to introduces faces objects, so they can be customized by user.

(will do in another PR)

**Comment by AdrieanKhisbe** [comment]
so so? :)

**Comment by johanvts** [comment]
Hi Adriean

I have made a v1.0 tag now and I have added you as a collaborator to the project. I really appreciate that you want to put in the work and I am sure it will be a lot smoother if I don't have to interfere constantly. I look forward to see what face customization can bring to the fireplace :), but I hope you agree with me that we should be careful not to bloat the project.

**Comment by AdrieanKhisbe** [comment]
_Thanks @johanvts_ !

> should be careful not to bloat the project.

for sure :)

**Comment by AdrieanKhisbe** [comment]
@johanvts I fixed the badges. (the last one would be good after the next melpa stable build).

Could you activate the travis and coverage CI: 
to do so, log with your github account to http://travis-ci.org and http://coveralls.io, and activate the repositery :)

**Comment by johanvts** [comment]
Should be turned on now.

**Comment by AdrieanKhisbe** [comment]
Perfect @johanvts !! :)
Just have to wait a new push that will trigger the build. :)

**Comment by AdrieanKhisbe** [comment]
will do with updating README about install

**Pull request merged**
